on: push

jobs:
  check-ls:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
  check-node:
    runs-on: windows-latest
    steps:
      - name: node-v
        run: node --version
