name: write good
on: push

permissions: {}

jobs:
  write-good:
    runs-on: ubuntu-latest
    steps:
      - name: read path
        use: actions/checkout@v4
        
      - run: npm install -g write-good
      - run: npm install glob
  
      - run: write-good test.md
